spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/operational_readiness
spring.datasource.username=sukalyon
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true